CREATE TABLE MANAGER( -- 관리자 테이블
M_ID  		VARCHAR2(1024)	NOT NULL	PRIMARY KEY,	-- 아이디
M_PWD  		VARCHAR2(1024)  	NOT NULL,			-- 비밀번호
M_MAIL    	VARCHAR2(1024)   	NOT NULL    	UNIQUE,		-- 이메일
M_ROOT 		NUMBER 	DEFAULT 0,			-- 루트관리자
M_RESTAURANT  	NUMBER 	DEFAULT 0,			-- 식당관리
M_REPORT    	NUMBER 	DEFAULT 0,			-- 신고관리
M_QNA   	NUMBER 	DEFAULT 0,			-- QnA 관리
M_MEMBER    	NUMBER 	DEFAULT 0,			-- 회원관리
M_FAQ   		NUMBER 	DEFAULT 0,			-- FAQ관리
M_NOTICE    	NUMBER 	DEFAULT 0			-- 공지관리
);
