CREATE TABLE MANAGER( -- 관리자 테이블
M_ID  		VARCHAR2(128)	NOT NULL	PRIMARY KEY,	-- 아이디
M_PWD  		VARCHAR2(128)  	NOT NULL,			-- 비밀번호
M_MAIL    	VARCHAR2(128)   	NOT NULL    	UNIQUE,		-- 이메일
M_ROOT 		BOOLEAN 	DEFAULT 0,			-- 루트관리자
M_RESTAURANT  	BOOLEAN 	DEFAULT 0,			-- 식당관리
M_REPORT    	BOOLEAN 	DEFAULT 0,			-- 신고관리
M_QNA   	BOOLEAN 	DEFAULT 0,			-- QnA 관리
M_MEMBER    	BOOLEAN 	DEFAULT 0,			-- 회원관리
M_FAQ   		BOOLEAN 	DEFAULT 0,			-- FAQ관리
M_NOTICE    	BOOLEAN 	DEFAULT 0			-- 공지관리
);
