CREATE TABLE MEMBER( -- 멤버 테이블
    MEMBER_NO        	NUMBER		NOT NULL	PRIMARY KEY,	-- 멤버 고유번호 (100번부터 시작 1씩 증가)
    MEMBER_NAME    	VARCHAR2(128)	NOT NULL,			-- 멤버명
    MEMBER_ID		VARCHAR2(128) 	NOT NULL	UNIQUE,		-- 멤버 아이디 (중복 불가)
    MEMBER_PWD 	    	VARCHAR2(128)	NOT NULL,			-- 멤버 비밀번호
    MEMBER_PHONE   	VARCHAR2(128)	NOT NULL,			-- 멤버 연락처
    MEMBER_BIRTH   	VARCHAR2(128)	NOT NULL,			-- 멤버 생년월일
    MEMBER_EMAIL    	VARCHAR2(128)  	NOT NULL	UNIQUE,		-- 멤버 이메일
    MEMBER_ADDRESS  	VARCHAR2(256)	NOT NULL,			-- 멤버 주소
);
CREATE SEQUENCE MEMBER_SEQ START WITH 100 INCREMENT BY 1 NOCYCLE;
SELECT*FROM MEMBER;