      
CREATE TABLE MENU( -- 메뉴 테이블
    MENU_NO       	NUMBER  	NOT NULL	PRIMARY KEY,	-- 메뉴 고유번호 (100번부터 시작 1씩 증가)
    MENU_NAME  	NVARCHAR2(1000)	NOT NULL,			-- 메뉴명
    MENU_PRICE   NUMBER		NOT NULL,               -- 메뉴가격
    MENU_RESTAURANT   NUMBER NOT NULL CONSTRAINT FK_MENU_R REFERENCES RESTAURANT(RESTAURANT_NO) ON DELETE CASCADE			-- 메뉴넣을 식당 FK ( RESTAURANT 테이블의 PK 참조 )
);

CREATE SEQUENCE MENU_SEQ START WITH 100 INCREMENT BY 1 NOCYCLE;