CREATE TABLE QNA( --고객센터 테이블
    QNA_NO       		NUMBER  	    NOT NULL	PRIMARY KEY,	-- 문의 번호 (100번부터 시작 1씩 증가)
    QNA_TITLE    		VARCHAR2(1024)	NOT NULL,			-- 문의 제목
    QNA_CONTENT 	VARCHAR2(4000)	NOT NULL,			-- 문의 내용
    QNA_REGDATE  	DATE		    NOT NULL,			-- 작성일
    QNA_WRITER  		NUMBER  CONSTRAINT FK_QNA REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,			-- 회원 작성자FK ( MEMBER 테이블 PK 참조 )
    QNA_NONMEMBER	VARCHAR2(1024),					-- 비회원 작성자
    QNA_PWD		VARCHAR2(1024)		NOT NULL,			-- 비회원 작성시 비밀번호
    QNA_PUBLIC		NUMBER	DEFAULT 0,			-- 공개여부 (기본값 0 비공개)
    QNA_REPLY		VARCHAR2(4000)					-- 답글
);

CREATE SEQUENCE QNA_SEQ START WITH 100 INCREMENT BY 1 NOCYCLE;
SELECT*FROM SERVICE;