CREATE TABLE QNA( -- 고객센터 QnA 테이블
    QNA_NO       		NUMBER  	NOT NULL	PRIMARY KEY,	-- 문의 번호 (100번부터 시작 1씩 증가)
    QNA_TITLE    		VARCHAR2(64)	NOT NULL,			-- 문의 제목
    QNA_CONTENT 	VARCHAR2(512)	NOT NULL,			-- 문의 내용
    QNA_REGDATE  	DATE		NOT NULL,			-- 작성일
    QNA_WRITER  		NUMBER,						-- 회원 작성자	FK ( MEMBER 테이블 PK 참조 )
    QNA_NONMEMBER	VARCHAR2(64),					-- 비회원 작성자
    QNA_PWD		VARCHAR2(64)	NOT NULL,			-- 비회원 작성시 비밀번호
    QNA_PUBLIC		NUMBER	DEFAULT 0,			-- 공개여부 (기본값 0 비공개)
    QNA_REPLY		VARCHAR2(512)					-- 답글
    CONSTRAINT 	
    FK_SERVICE FOREIGN KEY(QNA_WRITER) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
);

CREATE SEQUENCE QNA_SEQ START WITH 100 INCREMENT BY 1 NOCYCLE;
SELECT*FROM SERVICE;