CREATE TABLE RESTAURANT ( 
  RESTAURANT_NO		NUMBER(38)  	NOT NULL 	PRIMARY KEY,	-- 식당 고유번호
  RESTAURANT_NAME 	NVARCHAR2(128),					-- 식당명
  RESTAURANT_PH 	NVARCHAR2(128),					-- 식당 전화번호
  RESTAURANT_CATEGORY 	NVARCHAR2(128),					-- 식당 분류
  RESTAURANT_MENU 	NVARCHAR2(128),					-- 대표메뉴
  RESTAURANT_SI 		NVARCHAR2(128),					-- 시
  RESTAURANT_GU 	NVARCHAR2(128),					-- 구
  RESTAURANT_DONG 	NVARCHAR2(128),					-- 동
  RESTAURANT_ADDRESS 	NVARCHAR2(128),					-- 도로명 주소
  RESTAURANT_LATITUDE 	NUMBER(38, 7),					-- 위도
  RESTAURANT_LONGTITUDE NUMBER(38, 7)					-- 경도
);    

CREATE SEQUENCE RESTAURANT_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;	-- 시퀀스
SELECT*FROM RESTAURANT;

CREATE TRIGGER RES_TRI							-- 트리거
BEFORE INSERT
ON RESTAURANT FOR EACH ROW
BEGIN
SELECT RESTAURANT_SEQ.NEXTVAL INTO :new.RESTAURANT_NO FROM dual;
END;